spring.application.name=FormValidator

server.port = 10049

#server.servlet.context-path=/formvalidator  NOT WORKING

service.context.path = /processing

#spring.datasource.url = jdbc:postgresql://10.1.11.125:5432/preprod_dev
#spring.datasource.username = postgres
#spring.datasource.password = postgres
#spring.datasource.driver-class-name = org.postgresql.Driver

spring.r2dbc.url=r2dbc:postgresql://10.1.11.125:5432/preprod_dev
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres



eureka.client.service-url.defaultZone=http://10.1.11.100:7070/eureka/
eureka.client.should-unregister-on-shutdown=true
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost

aesAuthKey=e3nyflxiz86jb9ws

#Service URLS

metatdata.service = lb://SERVICEMETADATA/services/
formmgmt.service = lb://FORMDESIGNER/formmgmt/


#Unique Id generator config

id.generator.worker.id = 1	
id.generator.datacenter.id =1


#CIRCUIT BREAKER

resilience4j.circuitbreaker.instances.FORMDESIGNER.registerHealthIndicator true
resilience4j.circuitbreaker.instances.FORMDESIGNER.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.FORMDESIGNER.slidingWindowType=count-based
resilience4j.circuitbreaker.instances.FORMDESIGNER.slidingWindowSize=10
resilience4j.circuitbreaker.instances.FORMDESIGNER.failureRateThreshold=20
resilience4j.circuitbreaker.instances.FORMDESIGNER.slow-call-rate-threshold=30
resilience4j.circuitbreaker.instances.FORMDESIGNER.waitDurationInOpenState=60s
resilience4j.circuitbreaker.instances.FORMDESIGNER.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.FORMDESIGNER.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.circuitbreaker.instances.SERVICEMETADATA.registerHealthIndicator true
resilience4j.circuitbreaker.instances.SERVICEMETADATA.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.SERVICEMETADATA.slidingWindowType=count-based
resilience4j.circuitbreaker.instances.SERVICEMETADATA.slidingWindowSize=10
resilience4j.circuitbreaker.instances.SERVICEMETADATA.failureRateThreshold=20
resilience4j.circuitbreaker.instances.SERVICEMETADATA.slow-call-rate-threshold=30
resilience4j.circuitbreaker.instances.SERVICEMETADATA.waitDurationInOpenState=60s
resilience4j.circuitbreaker.instances.SERVICEMETADATA.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.SERVICEMETADATA.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.circuitbreaker.instances.default.registerHealthIndicator true
resilience4j.circuitbreaker.instances.default.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.default.slidingWindowType=count-based
resilience4j.circuitbreaker.instances.default.slidingWindowSize=10
resilience4j.circuitbreaker.instances.default.failureRateThreshold=20
resilience4j.circuitbreaker.instances.default.slow-call-rate-threshold=30
resilience4j.circuitbreaker.instances.default.waitDurationInOpenState=60s
resilience4j.circuitbreaker.instances.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.default.automatic-transition-from-open-to-half-open-enabled=true


instances.circuitBreaker.critical.error =  SERVICEMETADATA,FORMDESIGNER,FORMDESIGNERr

# Actuator Exposure
management.endpoints.web.exposure.include=health,circuitbreakers,metrics

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty=DEBUG
