spring.application.name=PROCESSING

server.port = 9091

#server.servlet.context-path=/formvalidator  NOT WORKING

service.context.path = /processing

#spring.datasource.url = jdbc:postgresql://10.1.11.125:5432/preprod_dev
#spring.datasource.username = postgres
#spring.datasource.password = postgres
#spring.datasource.driver-class-name = org.postgresql.Driver

spring.r2dbc.url=r2dbc:postgresql://10.1.11.100:9093/FormValidator
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=30
spring.r2dbc.pool.max-idle-time=30s
spring.r2dbc.pool.validation-query=SELECT 1


# Log SQL statements (for R2DBC Postgres)
logging.level.io.r2dbc.postgresql=INFO
logging.level.org.springframework.r2dbc=DEBUG
logging.level.io.r2dbc.spi.ConnectionFactory=INFO


eureka.client.service-url.defaultZone=http://10.1.11.100:7070/eureka/
eureka.client.should-unregister-on-shutdown=true
eureka.instance.prefer-ip-address=true
#eureka.instance.hostname=localhost

aesAuthKey=e3nyflxiz86jb9ws

#Service URLS
metatdata.service = lb://SERVICEMETADATA/services/
formmgmt.service = lb://FORMDESIGNER/formmgmt/
mvel.execution.service=lb://MVELEXECUTION/mvel/


#Unique Id generator config

id.generator.worker.id = 1
id.generator.datacenter.id =1


#CIRCUIT BREAKER

resilience4j.circuitbreaker.instances.FORMDESIGNER.registerHealthIndicator= true
resilience4j.circuitbreaker.instances.FORMDESIGNER.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.FORMDESIGNER.slidingWindowType=count-based
resilience4j.circuitbreaker.instances.FORMDESIGNER.slidingWindowSize=10
resilience4j.circuitbreaker.instances.FORMDESIGNER.failureRateThreshold=20
resilience4j.circuitbreaker.instances.FORMDESIGNER.slow-call-rate-threshold=30
resilience4j.circuitbreaker.instances.FORMDESIGNER.waitDurationInOpenState=60s
resilience4j.circuitbreaker.instances.FORMDESIGNER.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.FORMDESIGNER.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.circuitbreaker.instances.SERVICEMETADATA.registerHealthIndicator= true
resilience4j.circuitbreaker.instances.SERVICEMETADATA.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.SERVICEMETADATA.slidingWindowType=count-based
resilience4j.circuitbreaker.instances.SERVICEMETADATA.slidingWindowSize=10
resilience4j.circuitbreaker.instances.SERVICEMETADATA.failureRateThreshold=20
resilience4j.circuitbreaker.instances.SERVICEMETADATA.slow-call-rate-threshold=30
resilience4j.circuitbreaker.instances.SERVICEMETADATA.waitDurationInOpenState=60s
resilience4j.circuitbreaker.instances.SERVICEMETADATA.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.SERVICEMETADATA.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.circuitbreaker.instances.default.registerHealthIndicator true
resilience4j.circuitbreaker.instances.default.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.default.slidingWindowType=count-based
resilience4j.circuitbreaker.instances.default.slidingWindowSize=10
resilience4j.circuitbreaker.instances.default.failureRateThreshold=20
resilience4j.circuitbreaker.instances.default.slow-call-rate-threshold=30
resilience4j.circuitbreaker.instances.default.waitDurationInOpenState=60s
resilience4j.circuitbreaker.instances.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.default.automatic-transition-from-open-to-half-open-enabled=true


instances.circuitBreaker.critical.error =  SERVICEMETADATA,FORMDESIGNER

# Actuator Exposure
management.endpoints.web.exposure.include=health,circuitbreakers,metrics

logging.level.org.springframework.web=INFO
logging.level.org.springframework.web.servlet.mvc=INFO
logging.level.org.springframework.cloud.gateway=INFO
logging.level.reactor.netty=INFO


#kafka config
spring.kafka.bootstrap-servers=10.1.11.100:9092
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

#topics

push.form.submission.data.inbox.topic = processing_push_form_submission_data_to_inbox
new.application.form.transaction.redis.timeout.minutes = 120

# Redis configuration
spring.data.redis.host=10.1.11.100
spring.data.redis.password=password_new
spring.data.redis.port=6379
spring.data.redis.connect-timeout=1000ms
spring.data.redis.timeout=1000ms
spring.redis.jedis.pool.max-wait=1000ms

#Configure Setting (Not implemented)
disable.cache = N


logging.level.io.r2dbc.pool=DEBUG